sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    accessKeyId: LTAI5tQ46FyHy7ynQPcxm4rD
    accessKeySecret: PgMCVNNaRcyU8VSZXdKjLvZAF2eXIv
    bucketName: exam-web-tlias
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxc5707cea2a19044c
    secret: dd9cf0ab4238e7533af02696c27e53b0